id: opecha:P007008
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19861
  title: ཐབས་ལམ་སྙིང་པོའི་ཉམས་ལེན་གྱི་དམིགས་སྐོར་བྱ་ཚུལ་རྒྱུད་སྡེའི་ཡང་སྙིང་།
  volume:
    e08140034d8342d58220240429933f64:
      image_group_id: I8LS19863
      title: Volume 1 of thabs lam snying po'i nyams len gyi dmigs skor bya tshul
        rgyud sde'i yang snying /
      volume_number: 1
      total_pages: 312
  author: ''
ebook_metadata:
  title: ཐབས་ལམ་སྙིང་པོའི་ཉམས་ལེན་གྱི་དམིགས་སྐོར་བྱ་ཚུལ་རྒྱུད་སྡེའི་ཡང་སྙིང་།
  author: ''
  sku: P007008
  cover: cover.jpg
  layers:
  - pagination
