id: P007008
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19861
  title: ཐབས་ལམ་སྙིང་པོའི་ཉམས་ལེན་གྱི་དམིགས་སྐོར་བྱ་ཚུལ་རྒྱུད་སྡེའི་ཡང་སྙིང་།
  author: ''
  volumes:
    f73c87a78e574cd6ba9128afdae87025:
      image_group_id: I8LS19863
      title: ''
      volume_number: 1
      total_pages: 312
ebook_metadata:
  title: ཐབས་ལམ་སྙིང་པོའི་ཉམས་ལེན་གྱི་དམིགས་སྐོར་བྱ་ཚུལ་རྒྱུད་སྡེའི་ཡང་སྙིང་།
  author: ''
  sku: P007008
  cover: cover.jpg
  layers:
  - pagination
