id: IC15854C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:18:45+00:00'
last_modified: '2022-06-08T11:55:49.676509+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19861
  title: ཐབས་ལམ་སྙིང་པོའི་ཉམས་ལེན་གྱི་དམིགས་སྐོར་བྱ་ཚུལ་རྒྱུད་སྡེའི་ཡང་སྙིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    F95B:
      image_group_id: I8LS19863
      title: Volume 1 of thabs lam snying po'i nyams len gyi dmigs skor bya tshul
        rgyud sde'i yang snying /
      total_pages: 312
      order: 1
      base_file: F95B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
